Fmay/support dark mode
xtuml/bridgepoint pull request #807
Opened 2022-05-01 13:09 UTC by travislondon

Support Dark Mode

Current implementation looks at the current theme and
applies default colors accordingly.

NOTE: These changes do not listen for theme changes, but
we already get a notification from eclipse to restart before
changes take full effect.  Later support could be extended
to adjust when the theme changes.

Old workspaces will consider the previous defaults as user
configured due to the ui.text design.  New workspaces can be
created or in the OAL editor preferences "Restore Defaults"
can be used.

Graphics also uses a new default color scheme when dark mode
is used.

Support projects named differently than actual folder structure.

Eclipse allows you to name a project independently of the folder
on disk.  When you have this situattion Import Model Component
will create unresolvable proxies.  This can create an issue with
many areas of the tool, but the one being fixed here is that global
types are not available as the results are added to the proxy and
not the real element.  There is only one line that needs changing
to address this issue and in that case we were taking an eclipse
resource an converting it to a filesystem object.  This was unneccesary
as the full path of the resource object is the exact path we need.

2022-05-01 18:40 UTC, leviathan747 requested changes

2022-05-01 18:40 UTC, leviathan747 commented on src/org.xtuml.bp.core/src/org/xtuml/bp/core/util/UIUtil.java
> +		// revert to light mode
How are other plugins accessing the theme? Surely we are not the only one with custom elements that we want to follow the current theme.

2022-05-01 18:40 UTC, leviathan747 commented on src/org.xtuml.bp.io.core/arc/gen_import_java.inc
> +                    projRelPath = file.getFullPath();
This does not look related to the theme. Is this fixing a bug?

2022-05-01 18:40 UTC, leviathan747 commented on src/org.xtuml.bp.ui.graphics/src/org/xtuml/bp/ui/graphics/figures/ShapeImageFigure.java
> +			defaultColor = Activator.getDefault().getColor(81, 86, 88);
The color is modeled and loaded into the GD_ES instances from PEI data (defined in plugin.xml). If we are going to do this, let's properly model it. Perhaps we can add a new attribute for the dark mode color and then access the correct attribute based on the current mode.

2022-05-01 18:40 UTC, leviathan747 commented on src/org.xtuml.bp.ui.graphics/src/org/xtuml/bp/ui/graphics/parts/DiagramEditPart.java
> +		return Activator.getDefault().isDarkTheme() ? Activator.getDefault().getColor(47,47,47) : mdlSpec.getBackground();
Same as above comment.

2022-05-01 18:40 UTC, leviathan747 commented
Created issue: https://support.onefact.net/issues/12480

2022-05-01 18:41 UTC, leviathan747 commented on src/org.xtuml.bp.io.core/arc/gen_import_java.inc
> +                    projRelPath = file.getFullPath();
Ok, I just saw the comments in the PR on this. Please separate into a different branch/PR and associate with the appropriate issue.

2022-05-01 20:08 UTC, travislondon commented
I agree with the suggestions provided here, though I do not have much time to look into it at this point.  I suggest you dismiss this PR for now.  When I get a solution in place with the suggested changes I will offer a new PR.

2022-05-02 14:05 UTC, leviathan747 commented
Will do, however the change fixing the proxy issue sounds like it is worth merging now. If you peel that out into its own commit/branch, I will merge it into master.

2022-05-02 14:05 UTC, closed without merging